name: Flutter CI

on:
  workflow_dispatch:
    push:
      branches: [ main, develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
  flutter-check:
    name: Flutter Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Analyze Dart code using flutter_lint.yml
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings --options flutter_lint.yml

      - name: Check Dart formatting
        run: dart format . --output=none --set-exit-if-changed
